Updating scripts.

diff --git a/bash/run b/bash/run
--- a/bash/run
+++ b/bash/run
@@ -1,44 +1,70 @@
 #!/bin/bash
 
-if [ -e ./.environment ]; then
-	cat ./.environment
-	. ./.environment
-fi
+while [ ${PWD} != '/' ]
+do
 
-if [ -e .build/build.ninja ]; then
-	ninja -C .build
-	if [ "${?}" != "0" ]; then
-		exit ${?}
-	fi
-	if [ -z ${EXENAME}]; then
-		EXENAME=$(find .build -maxdepth 1 -type f -executable -print | grep -v '.so' | head --lines=1)
+	if [ -e ./.environment ]; then
+		cat ./.environment
+		. ./.environment
 	fi
 
-elif [ -e Makefile ]; then
-	make Debug
-	if [ "${?}" != "0" ]; then
-		exit ${?}
-	fi
-	if [ -z ${EXENAME}]; then
-		EXENAME=$(find .bin/Debug -maxdepth 1 -type f -executable -print | grep -v '.so' | head --lines=1)
-	fi
-fi
+	if [ -x ./run.sh ]; then
+		./run.sh ${@}
+		rc=${?}
+		echo "Custom script finished with rc=${rc}"
+		exit ${rc}
 
-if [ ! -z ${EXENAME} ]; then
-	echo "Running ${EXENAME} ..."
-	if [ -x /usr/bin/valgrind ]; then
-		touch valgrind.suppression
-		/usr/bin/valgrind \
-			--vgdb=no \
-			--leak-check=full \
-			--track-origins=yes \
-			--gen-suppressions=all \
-			--suppressions=valgrind.suppression \
+	elif [ -x ./.run.sh ]; then
+		echo ./run.sh ${@}
+		rc=${?}
+		echo "Custom script finished with rc=${rc}"
+		exit ${rc}
+
+	elif [ -e .build/build.ninja ]; then
+		ninja -C .build
+		if [ "${?}" != "0" ]; then
+			exit ${?}
+		fi
+		if [ -z ${EXENAME} ]; then
+			EXENAME=$(find .build -maxdepth 1 -type f -executable -print | grep -v '.so' | head --lines=1)
+		fi
+
+	elif [ -e Makefile ]; then
+		make Debug
+		if [ "${?}" != "0" ]; then
+			exit ${?}
+		fi
+		if [ -z ${EXENAME}]; then
+			EXENAME=$(find .bin/Debug -maxdepth 1 -type f -executable -print | grep -v '.so' | head --lines=1)
+		fi
+
+	fi
+
+	if [ ! -z ${EXENAME} ]; then
+		echo "${PWD}"
+		echo "Running ${EXENAME} ..."
+		if [ -x /usr/bin/valgrind ]; then
+			touch valgrind.suppression
+			/usr/bin/valgrind \
+				--vgdb=no \
+				--leak-check=full \
+				--track-origins=yes \
+				--gen-suppressions=all \
+				--suppressions=valgrind.suppression \
+				${EXENAME}
+		else
 			${EXENAME}
-	else
-		${EXENAME}
-	fi
-	exit ${?}	
-fi
+		fi
+		rc=${?}
+		echo "${EXENAME} exits with ${rc}"
+		exit ${rc}	
 
+	fi
+
+	cd ..
+
+done
+
+echo "Unable to find build system"
+exit 1
 
diff --git a/devel/build b/devel/build
--- a/devel/build
+++ b/devel/build
@@ -1,18 +1,29 @@
 #!/bin/bash
 
-if [ -e meson.build ]; then
-	meson compile -C .build
-	exit ${?}
-fi
+while [ ${PWD} != '/' ]
+do
 
-if [ -e .build/build.ninja ]; then
-	ninja -C .build
-	exit ${?}
-fi
+	if [ -e meson.build ]; then
+		echo "Building in ${PWD}..."
+		meson compile -C .build
+		exit ${?}
+	fi
 
-if [ -e Makefile ]; then
-	make Debug
-	exit ${?}
-fi
+	if [ -e .build/build.ninja ]; then
+		echo "Building in ${PWD}..."
+		ninja -C .build
+		exit ${?}
+	fi
 
+	if [ -e Makefile ]; then
+		echo "Building in ${PWD}..."
+		make Debug
+		exit ${?}
+	fi
 
+	cd ..
+
+done
+
+echo "Unable to file build system"
+exit 1
